spring.application.name=mayhotel

# ==========================================
# MONGODB
# ==========================================
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=MayHotelDB


# ==========================================
# Xác thực OTP dùng mật khẩu ứng dụng và email của Google
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cuongvoit2407@gmail.com
spring.mail.password=ijhx dvzx asou quii
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ==========================================
# Cấu hình Đường dẫn AI API Server (Colab Ngrok)
# Dùng để Backend Java gọi qua AI kiểm tra CCCD, No-show
# ==========================================
ai.server.url=https://espresso-shock-reenact.ngrok-free.dev/
