spring:
  application:
    name: mayhotel
  
  data:
    mongodb:
      uri: mongodb://localhost:27017/MayHotelDB
      
server:
  port: 8080

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
